#!/usr/bin/env ruby
# frozen_string_literal: true

# One way: if .remuda/Gemfile is here, that bundle is Remuda.
if ENV["BUNDLE_BIN_PATH"].to_s.empty?
  gemfile = File.expand_path(".remuda/Gemfile")
  exec({ "BUNDLE_GEMFILE" => gemfile }, "bundle", "exec", "remuda", *ARGV) if File.file?(gemfile)
end

require "remuda"

begin
  Remuda::CLI.start(ARGV)
rescue ArgumentError => e
  warn e.message
  exit 1
end
